# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: MAIN TITLE

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: MAIN TITLE

description: andydrew
author:
  name: andydrew
  email: ab@andydrew.uk
  github: andrew-bennett
  twitter: zifiy
  pinterest: asd123
  linkedin: asd123
  bio: Tagline
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
about_path: about.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
